from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(\d+)/$', views.calendar, name = 'calendar'),
	url(r'^register/$', views.register, name='register'),
	url(r'^register_doctor/$', views.registerDoctor, name='doctor registration'),
	url(r'^register_nurse/$', views.registerNurse, name='nurse registration'),
	url(r'^register_manager/$', views.registerManager, name='manager registration'),
	url(r'^register_secretary/$', views.registerSecretary, name='secretary registration'),
	url(r'^register_admin/$', views.registerAdmin, name='admin registration'),
	url(r'^patient_list/$', views.patientList, name='patient list'),
	url(r'^doctor_list/$', views.doctorList, name='doctor list'),
	url(r'^nurse_list/$', views.nurseList, name='nurse list'),
	url(r'^manager_list/$', views.managerList, name='manager list'),
	url(r'^secretary_list/$', views.secretaryList, name='secretary list'),
	url(r'^admin_list/$', views.adminList, name='admin list'),
	url(r'^update_patient/(.*)$', views.updatePatient, name='update patient'),
	url(r'^update_doctor/(.*)$', views.updateDoctor, name='update doctor'),
	url(r'^update_nurse/(.*)$', views.updateNurse, name='update nurse'),
	url(r'^update_manager/(.*)$', views.updateManager, name='update manager'),
	url(r'^update_secretary/(.*)$', views.updateSecretary, name='update secretary'),
	url(r'^update_admin/(.*)$', views.updateAdmin, name='update admin'),
	url(r'^write_message/(.*)$', views.writeMessage, name='write message'),
	url(r'^message_list/$', views.messageList, name='Message List'),
	url(r'^logs_list/$', views.logList, name='Log Entries'),
	url(r'^view_info/(.*)$', views.viewInfo, name='view information'),
	url(r'^login/(.*)/$', views.Login, name='login'),
	url(r'^user/', views.Main, name='Main'),
	url(r'^logout/$', views.user_logout, name='logout'),
	url(r'^calendar/$', views.calendar, name='calendar'),
	url(r'^month/$', views.month, name='month'),
	url(r'^month/(\d+)/(\d+)/$', views.month, name='month'),
	url(r'^day/(\d+)/(\d+)/(\d+)/$', views.day, name='day'),
	url(r'^doclist/(\d+)/(\d+)/(\d+)/(\w+)/(.*)/$', views.doclist, name='doclist'),
	url(r'^appointment/(\d+)/(\d+)/(\d+)/(\w+)/(.*)/(.*)/$', views.appointment, name='appointment'),
	url(r'^statistics/$', views.statistics, name='statistics'),
	url(r'^hospital_list/$', views.HospitalList, name='hospital list'),
	url(r'^admit_a/(.*)$', views.admit_a, name='select hospital'),
	url(r'^admit_b/(.*)/(.*)$', views.admit_b, name='admit'),
	url(r'^discharge/(.*)$', views.discharge, name='discharge from hospital'),
	url(r'^select_hospital/(.*)/$', views.SelectHospital, name='select hospital'),
	url(r'^pending_list/$', views.pending, name='pending list'),
	url(r'^approved/(.*)/(\w+)/$', views.approved, name='approved checking'),
]